name: All-Tests

on:
  pull_request:
    branches: [ master, development ]

jobs:
  all-tests:
    name: Test Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Rust Nightly
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Cargo build
        uses: actions-rs/cargo@v1
        with:
          command: build

      - name: Run test suite
        shell: bash
        working-directory: ./tests
        run: |
          chmod +x run_all_tests.sh
          bash run_all_tests.sh